"""Pratice with the basics of coding"""
print(2)
print('Howdy!')
print("Howdy!"[4])
print(2 < 5)
print(2 > 5)
print(True)
print(type(True))
print(type(2 < 5))
print(type(2))
print(type(2.0))
print(type("2"))
print(float(2))
print(type(float(2)))